### ISSUE TITLE
Arguments for a specific PID?

### ISSUE THREAD

**Issue by dsully** [BlackHoleFox/appleargs#3]
Is there any way to get the process arguments for a specific PID?

Thanks

**Comment by BlackHoleFox** [comment]
Heyo. So this library is for grabbing the arguments that Apple's kernel passes into your process space automatically for other system frameworks to read. And so are very different from the usual process arguments everyone is used to.

If you want to grab the command line/process arguments for something you need to use `proc_pidinfo` in `libproc.h` directly or use a crate such as [sysinfo](https://docs.rs/sysinfo/latest/sysinfo/struct.Process.html#method.cmd).

**Comment by dsully** [comment]
Noted! Thank you.
